/*
 * Filter Design and Analysis Tool - Generated Filter Coefficients - C Source 
 *  Generated by MATLAB - Signal Processing Toolbox
 */
//#pragma DATA_SECTION (COEFFS, "coeff_sect");

	

//Int16 COEFFS[12] = {-3030, 1592, 2733, 4236, 5607, 6416, 6416, 5607, 4236, 2733, 1592, -3030};// These filter coefficients are used for first exerscise.

//Int16 COEFFS[12] = {-30, 16, 27, 42, 56, 64, 64, 56, 42, 27, 16, -30};// These filter coefficients are used for first exerscise.

Int16 COEFFS[12] = {-60, 32, 54, 84, 112, 128, 128, 112, 84, 54, 32, -60};// These filter coefficients are used for first exerscise.

//Int16 COEFFS[12] = {1,0,0,0,0,0,0,0,0,0,0,0};// These filter coefficients are used for first exerscise.
